### ISSUE TITLE
Added Self Reflection

### ISSUE THREAD

**Issue by jonesna213** [jonesna213/Week-8-Exercise#2]
@pawaitemadisoncollege Self Reflection is completed.

**Comment by pawaitemadisoncollege** [comment]
Hi @jonesna213  Your self-evaluation level selections and comments are on target: accurately representing where you are in the ent java journey and what you need to progress. I think there are a few areas that would benefit from even more evidence/examples:

**Industry best practices** could also include: DRY principle (Don't Repeat Yourself) in java code and JSPs, using properties over hard-coding, properly using javabeans and expression language, and separation of concerns - ui stuff in the jsps, logic in the java code, small, single-purpose methods, abstracting similar functionality in way similar to the generic dao.

**Documentation** can also include some of the planning and tracking documents you've used on the Indie project.

**Build and deploy** also consider deployment to AWS.

**Git and GitHub** should also include working in a team environment (not only the student repo, but also collaborating on the team project), branching could be an important concept with the team project and even on your own project: using branches for features, rather than always working on main.

**Collaboration/Teamwork** - the upcoming team project should provide plenty opportunity here!

Moving forward, I recommend reviewing this document regularly (bi-weekly?) and try to add at least one brief example or summary of how your level of achievement has progressed in a category or two. I will try to highlight opportunities related to this as well.

Keep up the solid work!
